### ISSUE TITLE
Feature request: add 12 pre-defined byte combinations

### ISSUE THREAD

**Issue by ReforgedDream** [d1z1k/ComPortApplicatin#2]
Please add 12 buttons, to automatically send the following data:
1. 61 77 6B (ASCII "awk") (name or label: "R_REGISTER")
2. 62 77 6B (ASCII "bwk") (name or label: "W_REGISTER")
3. 63 77 6B (ASCII "cwk") (name or label: "R_RX_PAYLOAD")
4. 64 77 6B (ASCII "dwk") (name or label: "W_TX_PAYLOAD")
5. 65 77 6B (ASCII "ewk") (name or label: "FLUSH_TX")
6. 66 77 6B (ASCII "fwk") (name or label: "FLUSH_RX")
7. 67 77 6B (ASCII "gwk") (name or label: "REUSE_TX_PL")
8. 68 77 6B (ASCII "hwk") (name or label: "ACTIVATE")
9. 69 77 6B (ASCII "iwk") (name or label: "R_RX_PL_WID")
10. 6A 77 6B (ASCII "jwk") (name or label: "W_ACK_PAYLOAD")
11. 6B 77 6B (ASCII "kwk") (name or label: "W_TX_PAYLOAD_NOACK")
12. 6C 77 6B (ASCII "lwk") (name or label: "NOP")

**Comment by d1z1k** [comment]
add 12 buttons + auto send data
